name: Grammar Check

on: [pull_request]

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Vale with default configuration
      - name: Grammar Check
        uses: errata-ai/vale-action@v2.1.1
        with:
          args: --no-config # Explicitly tell Vale to skip .vale.ini
