name: Grammar Check

on: [pull_request]

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Vale using default rules (no .vale.ini)
      - name: Grammar Check
        uses: errata-ai/vale-action@v1
